import type { NotebookEntry, Notebook } from "@/types";

export type { NotebookEntry, Notebook };

export const NOTEBOOK_ID_PLACEHOLDER = "default";

export const FALLBACK_ENTRIES: NotebookEntry[] = [
  {
    id: "fe1",
    notebook_id: NOTEBOOK_ID_PLACEHOLDER,
    title: null,
    thought: "A notebook for women building the future.",
    slug: null,
    source_article_id: null,
    is_active: true,
    priority: 10,
    display_date: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "fe2",
    notebook_id: NOTEBOOK_ID_PLACEHOLDER,
    title: "Today I learned...",
    thought: "Today I learned that *curiosity* scales better than certainty.",
    slug: null,
    source_article_id: null,
    is_active: true,
    priority: 0,
    display_date: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "fe3",
    notebook_id: NOTEBOOK_ID_PLACEHOLDER,
    title: null,
    thought: "Some problems cannot be solved with code alone.",
    slug: null,
    source_article_id: null,
    is_active: true,
    priority: 0,
    display_date: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "fe4",
    notebook_id: NOTEBOOK_ID_PLACEHOLDER,
    title: null,
    thought: "Technology remembers. People forget.",
    slug: null,
    source_article_id: null,
    is_active: true,
    priority: 0,
    display_date: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "fe5",
    notebook_id: NOTEBOOK_ID_PLACEHOLDER,
    title: null,
    thought: "The smallest lesson today may become tomorrow's breakthrough.",
    slug: null,
    source_article_id: null,
    is_active: true,
    priority: 0,
    display_date: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "fe6",
    notebook_id: NOTEBOOK_ID_PLACEHOLDER,
    title: null,
    thought: "Every notebook begins with one blank page.",
    slug: null,
    source_article_id: null,
    is_active: true,
    priority: 0,
    display_date: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "fe7",
    notebook_id: NOTEBOOK_ID_PLACEHOLDER,
    title: null,
    thought: "There are questions no search engine can answer.",
    slug: null,
    source_article_id: null,
    is_active: true,
    priority: 0,
    display_date: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "fe8",
    notebook_id: NOTEBOOK_ID_PLACEHOLDER,
    title: null,
    thought: "Growth often looks like repeating the same difficult thing until it becomes ordinary.",
    slug: null,
    source_article_id: null,
    is_active: true,
    priority: 0,
    display_date: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
